### ISSUE TITLE
`Parse error: syntax error, unexpected 'ResponseFactoryInterface' (T_STRING)

### ISSUE THREAD

**Issue by eksimoron** [SpazzMarticus/TusServer-Example-Slim#1]
I install this repo but I have errors.

`Parse error: syntax error, unexpected 'ResponseFactoryInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /Users/Username/Sites/domain/vendor/spazzmarticus/tus-server/src/TusServer.php on line 40`

How can I fix it?

**Comment by SpazzMarticus** [comment]
Hi,

this repo requires at least PHP Version 7.4, because [typed properties](https://www.php.net/manual/en/language.oop5.properties.php#language.oop5.properties.typed-properties) are used.

I will add the requirement to composer.json.

**Comment by SpazzMarticus** [comment]
Fixed with [TusServer ^1.0](https://github.com/SpazzMarticus/TusServer/releases/tag/1.0.0) and current example version
